apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: factorial
  creationTimestamp: null
  labels:
    app: my-factorial-app
  name: my-factorial-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-factorial-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-factorial-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: hyuklassic/factorial-app:0.0.6
        name: factorial-app
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Gi"
            cpu: "2000m"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 10"]
        startupProbe:
          httpGet:
            path: /probe/startup
            port: 8080
          initialDelaySeconds: 30
          failureThreshold: 10
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /probe/ready
            port: 8080
          initialDelaySeconds: 15
          failureThreshold: 3
          successThreshold: 2
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /probe/live
            port: 8080
          initialDelaySeconds: 15
          failureThreshold: 7
          periodSeconds: 1
status: {}
