apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: factorial-hpa
  namespace: factorial
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: my-factorial-app
    minReplicas: 2
    maxReplicas: 5
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 30
      scaleUp:
        stabilizationWindowSeconds: 30